[connections.mysql]
dialect = "mysql"
driver = "pymysql"
host = "sql12.freesqldatabase.com"         # e.g., "localhost" or a remote URL
port = 3306
database = "sql12805466"
username = "sql12805466"
password = "mTTThRHFs4"
